### ISSUE TITLE
15 Concept List Project

### ISSUE THREAD

**Issue by LinguList** [concepticon/concepticon-data#1158]
@marthuis, @chrzyki, we use this to tackle the 15 concept lists (10 concepticon concept lists, 5 NoRaRe concept lists)

When editing with LibreOffice any files (preferably, one edits in text files only), one should select `\t` as separator, but not use `"` as quote char, but leave this blank. This caused problems in #1154, which I just solved.

## Concepticon
I suggest 3 lists here, more can then be suggested by @chrzyki and @marthuis, or by myself

- [x] #1131 Sidwell's concept list for Vietic languages (116 items) 
- [x]  #1129 Concept list by Epps (nouns, 800, Swedish and English)
- [ ] #925 short 60 concept list (stimuli) derived from Concepticon 

## NoRaRe

These are my suggestions for NoRaRe datasets (which can be manually mapped), but @AnnikaTjuka should suggest or modify this collection, as this is supposed to contribute to NoRaRe (I will explain in an email on Monday)

- [x] #1152 Core Vocabulary with Frequencies (ca 3000 items)
- [x] #1135 90 Chinese Words
- [ ] #1156 Swadesh list with Bulgarian entries (will lead to new language entry) 
- [ ] #1133 Word sense data (500 items) from a historical thesaurus
- [x] #1127 Emotion Circle in Four Languages (short list)

**Comment by marthuis** [comment]
Hi Mattis, thank you for putting up this list. Upon looking, I noticed the following open issue: 

- #998 

Somebody asked there whether the list was still worth adding. What are your thoughts?

**Comment by LinguList** [comment]
@marthuis, should we proceed with the open issue first? I have fixed the dating problems, so you'd have to ideally make sure to git-pull the latest version of conceptlists.tsv, and edit it accordingly (paying attention to not introduce `"` and other things when working with Excel or LibreOffice.

**Comment by LinguList** [comment]
Yes, that seems like a good idea!

**Comment by AnnikaTjuka** [comment]
Okay, will do it by the end of the week!

**Comment by AnnikaTjuka** [comment]
That's the list in #1135, right? It's a great list for NoRaRe and could easily be mapped manually and added to Concepticon.

**Comment by LinguList** [comment]
@marthuis, can you indicate, when you will look into this, and please also tell us approximately, when you want to to catch up with #1153? I will have to make plans for the things I want to work on during the next week, and it would be good to get started here.

**Comment by marthuis** [comment]
@LinguList Hi Mattis, the catch up for #1153 will be ready by the end of week, I have some new concepts in the commit as well. Next can be #1135. For NoRaRe, the priority is #1152 if I followed correctly, right? For the rest, I experimented extracting #998 and that should be finished soon as well, but I won't make it priority for now, just letting you know it's semi-done. The #1156 for NoRaRe can be also a possibility, depending on which one is more urgent. What do you think of the following order?

- # 1153
- # 1135
- # 1152 or #1156?

**Comment by LinguList** [comment]
This is fine. I think the most important aspect now is that we get the open issue closed (where I gave instructions of how to circumvent the problem of autoformatted entries, which I already fixed and now need to be used in your mappings). Judging from how that goes, we can also predict how well the other lists can be added then. But my first priority is now to have this issue closed ;)

**Comment by AnnikaTjuka** [comment]
@marthuis and @LinguList I just checked NoRaRe and we have already added the Core Vocabulary List from https://github.com/concepticon/concepticon-data/issues/1152 to NoRaRe. So this item can be ticked off the list.

**Comment by marthuis** [comment]
@LinguList #1135 is almost ready, I'll create a PR on a different branch this time, once #1153 is closed!

Moreover, I have a suggestion for a new list (Concepticon): 
[https://llacan.cnrs.fr/SBB/afficheSeries.html](url)

It's a rich comparative historical lexicon for several Nilo-Saharan languages, glossed in French, and it seems to contain new colexifications. What do you think? :)

**Comment by LinguList** [comment]
Yes, this list could definitely be added, but to do so, we should make an issue where we discuss this in detail (also what to add to the concept list etc.).

**Comment by AnnikaTjuka** [comment]
I assigned the open lists to @mathildavz. So I'm going to close this issue now.
